@OpsControl.Api_HostAddress = http://localhost:5034

GET {{OpsControl.Api_HostAddress}}/weatherforecast/
Accept: application/json

###
GET https://localhost:7085/api/incidents/6
###
GET https://localhost:7085/api/incidents/
###
GET https://localhost:7085/api/incidents?status=New
###
POST https://localhost:7085/api/incidents
Content-Type: application/json

{
  
  "title": "El servidor ardió",
  "description": "El esta en llamaradas",
  "impact": "",
  "urgency": "High"
}

###
PUT https://localhost:7085/api/incidents/5
Content-Type: application/json

{
  "title": "el bug no se corrigió en enero",
  "description": "el bug 333434 falla modificado."
}
###
PUT https://localhost:7085/api/incidents/6/start
###
###
GET https://localhost:7085/api/incidents/summary
###
PUT https://localhost:7085/api/incidents/111/resolve/
###

DELETE https://localhost:7085/api/incidents/3

###
GET https://localhost:7085/api/incidents?status=new
###
GET https://localhost:7085/api/incidents?status=new&page=1&pageSize=1
###


GET https://localhost:7085/api/incidents
###
GET https://localhost:7085/api/incidents?page=1&pageSize=2
###
GET https://localhost:7085/api/incidents?status=Resolved
###

GET https://localhost:7085/api/incidents?page=0
###