@OpsControl.Api_HostAddress = http://localhost:5034

GET {{OpsControl.Api_HostAddress}}/weatherforecast/
Accept: application/json

###
GET https://localhost:7085/api/incidents/1
###
GET https://localhost:7085/api/incidents/
###
GET https://localhost:7085/api/incidents?status=New
###
POST https://localhost:7085/api/incidents
Content-Type: application/json

{
  
  "title": "Servidor de producción caído",
  "description": "El servidor no responde",
  "impact": "High",
  "urgency": "High"
}

###
PUT https://localhost:7085/api/incidents/2
Content-Type: application/json

{
  "title": "",
  "description": "Primera prueba del endpoint POSTmodificadisima."
}
###
PUT https://localhost:7085/api/incidents/1/start
###

DELETE https://localhost:7085/api/incidents/2

###
GET https://localhost:7085/api/incidents?status=new
###
GET https://localhost:7085/api/incidents?status=new&page=1&pageSize=1
###